version: "3"
services:
  chatbot:
    image: comp7940chatbot
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    image: comp7940sql
    # port mapping
    ports:
      - "3306:3306"
    expose:
      - "3306"
