version: "3"
services:
  chatbot:
    image: comp7940chatbot1
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - "5000:5000"
  mysql:
    image: comp7940sql1
    # port mapping
    ports:
      - "3306:3306"
    expose:
      - "3306"
