name: CI/CD 
on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    name: cicd
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : 'ec2-user'
            USER_NAME : 'ec2-18-163-195-22.ap-east-1.compute.amazonaws.com'
            
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile /dev/null" -i private_key ${USER_NAME}@${HOSTNAME} '
          
            #Now we have got the access of EC2 and we will start the deploy .
            cd /home/ec2-user/COMP7940_GroupProj_40 &&
            git checkout main &&
            git fetch --all &&
            git reset --hard origin/main &&
            git pull origin master &&
            docker-compose -f docker-compose.prod.yml up -d --build 
          '
