name: Deploy EC2
on: push
jobs:
  merge-PR:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.AWS_SSH_KEY  }}
          name: "ec2-user"
          known_hosts: "ec2-16-162-122-188.ap-east-1.compute.amazonaws.com"
      - name: rsync over ssh
        run: ./deploy_to_aws.sh
