name: Deploy EC2
on: push
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.AWS_PRIVATE_KEY  }}
          name: "ec2-user"
          known_hosts: ${{ secrets.USER_NAME  }}
      - name: rsync over ssh
        run: ./deploy_to_aws.sh
